[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference="Stop"
$repoRoot=Split-Path -Parent $PSScriptRoot
$verifyScript=Join-Path $repoRoot "scripts\verify.ps1"
$generatorScript=Join-Path $repoRoot "scripts\new-verification-profile.ps1"
$scriptsToParse=@("scripts\detect-stack.ps1","scripts\policy-check.ps1","scripts\verify.ps1","scripts\new-verification-profile.ps1","installer\install.ps1","installer\doctor.ps1")
foreach($relative in $scriptsToParse){$path=Join-Path $repoRoot $relative;$tokens=$null;$errors=$null;[System.Management.Automation.Language.Parser]::ParseFile($path,[ref]$tokens,[ref]$errors)|Out-Null;if($errors.Count -gt 0){throw "PowerShell parse failure in $relative`: $($errors[0].Message)"}}
$temp=Join-Path ([System.IO.Path]::GetTempPath()) ("copilot-harness-smoke-"+[Guid]::NewGuid().ToString("N"));New-Item -ItemType Directory -Path $temp -Force|Out-Null
function Assert-PolicyExit{param([string]$ExpectedClass,[string]$ExpectedDecision,[int]$ExpectedExit,[hashtable]$Arguments);$jsonText=(&(Join-Path $repoRoot "scripts\policy-check.ps1") @Arguments -Json|Out-String);$actualExit=$LASTEXITCODE;if($actualExit-ne$ExpectedExit){throw "Policy exit mismatch. Expected $ExpectedExit, got $actualExit."};$result=$jsonText|ConvertFrom-Json;if($result.Classification-ne$ExpectedClass-or$result.Decision-ne$ExpectedDecision){throw "Policy result mismatch."}}
function New-VerifyFixture{param([string]$Name);$path=Join-Path $temp $Name;New-Item -ItemType Directory -Path $path -Force|Out-Null;Set-Content -LiteralPath(Join-Path $path "README.md") -Value "fixture";Push-Location $path;try{& git init --quiet;if($LASTEXITCODE-ne 0){throw "Failed to initialize Git fixture."}}finally{Pop-Location};return $path}
function Invoke-VerifyJson{param([string]$Target,[string]$ChangeType="docs",[string]$ProfilePath);if($ProfilePath){$text=(&$verifyScript -TargetPath $Target -ChangeType $ChangeType -ProfilePath $ProfilePath -Json|Out-String)}else{$text=(&$verifyScript -TargetPath $Target -ChangeType $ChangeType -Json|Out-String)};$verifyExit=$LASTEXITCODE;return[pscustomobject]@{Exit=$verifyExit;Data=($text|ConvertFrom-Json)}}
function Write-Profile{param([string]$Path,[object]$Profile);$Profile|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $Path -Encoding UTF8}
try{
 Set-Content -LiteralPath(Join-Path $temp "sample.sln") -Value "";Set-Content -LiteralPath(Join-Path $temp "angular.json") -Value "{}";Set-Content -LiteralPath(Join-Path $temp "package.json") -Value '{"dependencies":{"mongodb":"latest"}}';$result=&(Join-Path $repoRoot "scripts\detect-stack.ps1") -Path $temp;foreach($expected in @("DotNet","Angular","MongoDb")){if($result.DetectedStacks-notcontains$expected){throw "Expected stack '$expected' was not detected."}}
 Assert-PolicyExit "A0" "ALLOW" 0 @{ActionKind="read"};Assert-PolicyExit "A3" "REQUIRE_INTENT" 20 @{ActionKind="remote-mutate";Environment="shared"};Assert-PolicyExit "A3" "ALLOW" 0 @{ActionKind="remote-mutate";Environment="shared";ExplicitIntent=$true};Assert-PolicyExit "A4" "REQUIRE_APPROVAL" 30 @{ActionKind="destructive";Environment="production"};Assert-PolicyExit "A4" "ALLOW" 0 @{ActionKind="destructive";Environment="production";ImmediateApproval=$true}
 $docsFixture=New-VerifyFixture "docs";$docs=Invoke-VerifyJson $docsFixture;if($docs.Exit-ne 0-or-not$docs.Data.Ready){throw "Documentation fallback fixture should be ready."}
 $profileFixture=New-VerifyFixture "profile-pass";$profilePath=Join-Path $profileFixture ".copilot-harness.verify.json";Write-Profile $profilePath ([ordered]@{schemaVersion=1;checks=@([ordered]@{id="V1-PROFILE-PASS";name="Profile pass";changeTypes=@("docs");verificationLevel="V1";policyClass="A1";command="powershell";args=@("-NoProfile","-Command","exit 0");required=$true})});$pass=Invoke-VerifyJson $profileFixture;if($pass.Exit-ne 0-or-not$pass.Data.Ready-or@($pass.Data.Results|Where-Object{$_.Id-eq"V1-PROFILE-PASS"-and$_.State-eq"PASS"}).Count-ne 1){throw "Allowed A1 profile should execute and PASS."}
 $explicitFixture=New-VerifyFixture "profile-explicit";$explicitPath=Join-Path $temp "explicit-profile.json";Write-Profile $explicitPath ([ordered]@{schemaVersion=1;checks=@([ordered]@{id="V1-EXPLICIT";name="Explicit profile";changeTypes=@("dotnet");verificationLevel="V1";policyClass="A1";command="powershell";args=@("-NoProfile","-Command","exit 0")})});$explicit=Invoke-VerifyJson $explicitFixture "docs" $explicitPath;if($explicit.Exit-ne 0-or@($explicit.Data.Results|Where-Object{$_.Id-eq"V1-EXPLICIT"-and$_.State-eq"SKIPPED"}).Count-ne 1){throw "Explicit profile should load and nonmatching change type should SKIP."}
 $failFixture=New-VerifyFixture "profile-fail";Write-Profile(Join-Path $failFixture ".copilot-harness.verify.json")([ordered]@{schemaVersion=1;checks=@([ordered]@{id="V2-EXPECTED-FAIL";name="Expected child failure";changeTypes=@("all");verificationLevel="V2";policyClass="A1";command="powershell";args=@("-NoProfile","-Command","exit 7")})});$failed=Invoke-VerifyJson $failFixture;if($failed.Exit-ne 1-or@($failed.Data.Results|Where-Object{$_.Id-eq"V2-EXPECTED-FAIL"-and$_.State-eq"FAIL"}).Count-ne 1){throw "Failed child command must produce FAIL/exit 1."}
 foreach($policyClass in @("A2","A3","A4")){$blockedFixture=New-VerifyFixture("profile-"+$policyClass.ToLowerInvariant());Write-Profile(Join-Path $blockedFixture ".copilot-harness.verify.json")([ordered]@{schemaVersion=1;checks=@([ordered]@{id="POLICY-$policyClass";name="Blocked $policyClass";changeTypes=@("all");verificationLevel="V1";policyClass=$policyClass;command="powershell";args=@("-NoProfile","-Command","exit 0")})});$blocked=Invoke-VerifyJson $blockedFixture;if($blocked.Exit-ne 2-or@($blocked.Data.Results|Where-Object{$_.Id-eq"POLICY-$policyClass"-and$_.State-eq"BLOCKED"}).Count-ne 1){throw "$policyClass profile action must be BLOCKED/exit 2."}}
 $allowFixture=New-VerifyFixture "profile-allowlist";Write-Profile(Join-Path $allowFixture ".copilot-harness.verify.json")([ordered]@{schemaVersion=1;checks=@([ordered]@{id="ALLOWLIST";name="Disallowed executable";changeTypes=@("all");verificationLevel="V1";policyClass="A1";command="cmd";args=@("/c","exit 0")})});$allow=Invoke-VerifyJson $allowFixture;if($allow.Exit-ne 2){throw "Non-allowlisted executable must be BLOCKED."}
 $badJsonFixture=New-VerifyFixture "profile-bad-json";Set-Content -LiteralPath(Join-Path $badJsonFixture ".copilot-harness.verify.json") -Value '{bad json';$badJson=Invoke-VerifyJson $badJsonFixture;if($badJson.Exit-ne 1){throw "Malformed profile must FAIL closed."}
 $badSchemaFixture=New-VerifyFixture "profile-bad-schema";Write-Profile(Join-Path $badSchemaFixture ".copilot-harness.verify.json")([ordered]@{schemaVersion=999;checks=@()});$badSchema=Invoke-VerifyJson $badSchemaFixture;if($badSchema.Exit-ne 1){throw "Unsupported schema must FAIL closed."}
 $missingFixture=New-VerifyFixture "profile-missing-fields";Write-Profile(Join-Path $missingFixture ".copilot-harness.verify.json")([ordered]@{schemaVersion=1;checks=@([ordered]@{id="MISSING";name="Missing command";verificationLevel="V1";policyClass="A1"})});$missing=Invoke-VerifyJson $missingFixture;if($missing.Exit-ne 1){throw "Missing required profile fields must FAIL closed."}

 # Stack-aware generator: .NET + Angular scripts produce only known local A1 checks.
 $genFixture=New-VerifyFixture "generator";Set-Content -LiteralPath(Join-Path $genFixture "app.sln") -Value "";Set-Content -LiteralPath(Join-Path $genFixture "angular.json") -Value "{}";Set-Content -LiteralPath(Join-Path $genFixture "package.json") -Value '{"scripts":{"lint":"ng lint","test:ci":"ng test --watch=false"},"dependencies":{"@angular/core":"latest"}}';$genText=(&$generatorScript -TargetPath $genFixture -Json|Out-String);if($LASTEXITCODE-ne 0){throw "Stack-aware generator failed."};$genResult=$genText|ConvertFrom-Json;$generated=Get-Content -LiteralPath(Join-Path $genFixture ".copilot-harness.verify.json") -Raw|ConvertFrom-Json;$ids=@($generated.checks.id);foreach($id in @("V1-DOTNET-BUILD","V2-DOTNET-TEST","V1-ANGULAR-LINT","V2-ANGULAR-TEST")){if($ids-notcontains$id){throw "Generated profile missing $id."}};if(@($generated.checks|Where-Object{$_.policyClass-ne"A1"}).Count-ne 0){throw "Generator emitted non-A1 executable check."};if($genResult.GeneratedChecks-ne 4){throw "Expected four generated executable checks."}

 # Existing profile preservation: generation without -Force must fail and leave bytes unchanged.
 $before=Get-Content -LiteralPath(Join-Path $genFixture ".copilot-harness.verify.json") -Raw;$preserveFailed=$false;try{&$generatorScript -TargetPath $genFixture *> $null}catch{$preserveFailed=$true};$after=Get-Content -LiteralPath(Join-Path $genFixture ".copilot-harness.verify.json") -Raw;if(-not$preserveFailed-or$before-ne$after){throw "Generator must preserve an existing profile unless -Force is explicit."}

 # Data/cloud signals generate recommendations, never guessed executable remote checks.
 $dataFixture=New-VerifyFixture "generator-data";Set-Content -LiteralPath(Join-Path $dataFixture "warehouse.sql") -Value "SELECT 1; -- snowflake";Set-Content -LiteralPath(Join-Path $dataFixture "azure-pipelines.yml") -Value "trigger: none";Set-Content -LiteralPath(Join-Path $dataFixture "jfrog.config") -Value "jfrog";&$generatorScript -TargetPath $dataFixture *> $null;$dataProfile=Get-Content -LiteralPath(Join-Path $dataFixture ".copilot-harness.verify.json") -Raw|ConvertFrom-Json;if(@($dataProfile.checks).Count-ne 0){throw "Data/platform-only fixture must not receive guessed executable checks."};if(@($dataProfile.recommendations).Count-lt 1){throw "Detected data/platform signals should produce review recommendations."}

 Write-Host "PASS: PowerShell scripts parse successfully.";Write-Host "PASS: Existing policy and verification adversarial fixtures passed.";Write-Host "PASS: Stack-aware generator emits deterministic .NET/Angular A1 checks.";Write-Host "PASS: Generator preserves repository-owned profiles by default.";Write-Host "PASS: Data/platform detections produce recommendations rather than guessed remote commands.";$global:LASTEXITCODE=0;exit 0
}finally{Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue}
