[CmdletBinding()]
param(
    [Parameter(Position = 0)] [string]$TargetPath = ".",
    [ValidateSet("commands", "skills")] [string]$ExpectedSpecKitLayout = "commands",
    [string[]]$ExpectedSpecKitExtensions = @("git", "bug", "assess")
)
Set-StrictMode -Version Latest
$ErrorActionPreference="Stop"
$harnessRoot=Split-Path -Parent $PSScriptRoot; $targetRoot=(Resolve-Path -LiteralPath $TargetPath).Path; $detectScript=Join-Path $harnessRoot "scripts\detect-stack.ps1"; $stack=& $detectScript -Path $targetRoot; $specKitRepository="https://github.com/github/spec-kit"; $checks=New-Object System.Collections.Generic.List[object]
function Add-Check{param([string]$Name,[ValidateSet("PASS","WARN","FAIL")][string]$Status,[string]$Detail);[void]$checks.Add([pscustomobject]@{Name=$Name;Status=$Status;Detail=$Detail})}
function Test-CommandCheck{param([string]$Command,[bool]$Required,[string]$Reason);$found=Get-Command $Command -ErrorAction SilentlyContinue;if($null-ne$found){Add-Check "tool:$Command" "PASS" $found.Source}elseif($Required){Add-Check "tool:$Command" "FAIL" $Reason}else{Add-Check "tool:$Command" "WARN" $Reason}}
function Test-FileCheck{param([string]$RelativePath,[bool]$Required=$true);$path=Join-Path $targetRoot $RelativePath;if(Test-Path -LiteralPath $path -PathType Leaf){Add-Check "file:$RelativePath" "PASS" "present"}elseif($Required){Add-Check "file:$RelativePath" "FAIL" "missing"}else{Add-Check "file:$RelativePath" "WARN" "not installed"}}
if($env:OS -eq "Windows_NT"){Add-Check "platform" "PASS" "Windows"}else{Add-Check "platform" "WARN" "Harness is designed and supported primarily for Windows workstations."}
Test-CommandCheck "git" $true "Git is required for the repository workflow.";Test-CommandCheck "gh" $true "GitHub CLI is required by the approved workflow.";Test-CommandCheck "specify" $false "Install the official github/spec-kit specify-cli from $specKitRepository.";Test-CommandCheck "uv" $false "uv is the recommended installer/runtime for specify-cli."
if($stack.Signals.DotNet){Test-CommandCheck "dotnet" $true ".NET was detected in this repository."};if($stack.Signals.Angular){Test-CommandCheck "node" $true "Angular was detected in this repository.";Test-CommandCheck "npm" $true "Angular was detected in this repository."};if($stack.Signals.AzureDevOps){Test-CommandCheck "az" $false "Azure DevOps signals were detected; Azure CLI is recommended for approved CLI workflows."};if($stack.Signals.JFrog){Test-CommandCheck "jf" $false "JFrog signals were detected; JFrog CLI is recommended for compliance/artifact workflows."}
$requiredFiles=@(".github\copilot-instructions.md",".github\instructions\tests.instructions.md",".github\instructions\release-testing.instructions.md",".github\instructions\policy-verification.instructions.md",".github\prompts\feature.prompt.md","spec-kit\constitution-template.md","docs\POLICY-GATE.md","docs\VERIFICATION-CONTRACT.md","docs\SPECKIT-EXTENSIONS-VALIDATION.md","docs\RELEASE-TESTING.md","docs\releases\TESTING-TEMPLATE.md","docs\STACK-AWARE-VERIFICATION.md","scripts\policy-check.ps1","scripts\verify.ps1","scripts\new-verification-profile.ps1");foreach($f in $requiredFiles){Test-FileCheck $f}
if($stack.Signals.DotNet){Test-FileCheck ".github\instructions\dotnet.instructions.md"};if($stack.Signals.Angular){Test-FileCheck ".github\instructions\angular.instructions.md"};if($stack.Signals.SqlServer -or $stack.Signals.MongoDb -or $stack.Signals.Snowflake -or $stack.Signals.Parquet){Test-FileCheck ".github\instructions\data.instructions.md"}
$profilePath=Join-Path $targetRoot ".copilot-harness.verify.json"
if(Test-Path -LiteralPath $profilePath -PathType Leaf){
 try{$profile=Get-Content -LiteralPath $profilePath -Raw|ConvertFrom-Json;if($profile.schemaVersion -ne 1){Add-Check "verification:profile" "FAIL" "unsupported schemaVersion"}elseif($null -eq $profile.checks){Add-Check "verification:profile" "FAIL" "checks property missing"}else{Add-Check "verification:profile" "PASS" "schemaVersion 1 profile is parseable"; $unsafe=@($profile.checks|Where-Object{$_.policyClass -notin @("A0","A1")});if($unsafe.Count -gt 0){Add-Check "verification:profile-policy" "WARN" "$($unsafe.Count) check(s) require separate authorization and will be blocked by verify.ps1"}else{Add-Check "verification:profile-policy" "PASS" "automatic checks are A0/A1 only"}}}catch{Add-Check "verification:profile" "FAIL" "invalid JSON: $($_.Exception.Message)"}
}else{Add-Check "verification:profile" "WARN" "No .copilot-harness.verify.json found; run scripts/new-verification-profile.ps1 or configure one explicitly."}
$specKitMarker=Join-Path $targetRoot ".specify";if(Test-Path -LiteralPath $specKitMarker){Add-Check "spec-kit" "PASS" ".specify directory detected; expected source of truth is $specKitRepository"}else{Add-Check "spec-kit" "WARN" "Official github/spec-kit is not initialized in this repository yet."}
$manifestPath=Join-Path $targetRoot ".copilot-harness.json";if(Test-Path -LiteralPath $manifestPath -PathType Leaf){Add-Check "manifest" "PASS" ".copilot-harness.json present";try{$manifest=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json;if($null-ne$manifest.specKit -and $manifest.specKit.repository -eq $specKitRepository){Add-Check "manifest:spec-kit-source" "PASS" $specKitRepository}else{Add-Check "manifest:spec-kit-source" "WARN" "manifest does not record official github/spec-kit"};if($null-ne$manifest.verification -and $manifest.verification.runner -eq "scripts/verify.ps1" -and $manifest.verification.profileGenerator -eq "scripts/new-verification-profile.ps1"){Add-Check "manifest:verification" "PASS" "runner and profile generator recorded"}else{Add-Check "manifest:verification" "WARN" "manifest does not record stack-aware verification assets"}}catch{Add-Check "manifest:json" "WARN" "manifest could not be parsed as JSON."}}else{Add-Check "manifest" "WARN" "No installer manifest found; repository may have been configured manually."}
Write-Host "";Write-Host "Copilot Harness Doctor";Write-Host "Repository: $targetRoot";Write-Host "Detected stacks: $(if(@($stack.DetectedStacks).Count){@($stack.DetectedStacks)-join ', '}else{'none'})";Write-Host "Expected Spec Kit source: $specKitRepository";Write-Host "Verification profile: .copilot-harness.verify.json";Write-Host "";foreach($check in $checks){Write-Host ("[{0,-4}] {1,-45} {2}" -f $check.Status,$check.Name,$check.Detail)};$failures=@($checks|Where-Object Status -eq "FAIL");$warnings=@($checks|Where-Object Status -eq "WARN");Write-Host "";Write-Host ("Summary: {0} passed, {1} warnings, {2} failures" -f @($checks|Where-Object Status -eq "PASS").Count,$warnings.Count,$failures.Count);if($failures.Count -gt 0){exit 1};exit 0
